### PR TITLE
Make grove.py stable on Raspberry Pi 4 and 5

### PR DESCRIPTION
**Pull request by quietCoder500**
All references to MRAA and UPM were removed. The JHD1802, SH1107G, and MCP9808-I2C grove modules are now unsupported and are removed. They will need to be rewritten using Smbus2. The install script will also need to be completely redone.

### CODE REVIEW

**Comment by takanotume24** [comment]
The dependence on MRAA and UPM made it obviously difficult to apply to the recent Raspberry Pi OS. 
If removing support for some of the modules would improve the stability of the library, it would be a good choice.
I am just one user, but thanks.

**Comment by MatthewJeffson** [comment]
Wow! Thank you @quietCoder500

**Comment by quietCoder500** [comment]
All three modules (JHD1802, SH1107G, and MCP9808-I2C) were all I2C devices that used MRAA and UPM's I2C abilities. I believe gpiozero has support for I2C, along with PWM, which can make it easier to support other modules. Does anyone have an opinion as to whether gpiozero should be used or not to rebuild this library? It is high-level but well supported and used probably by thousands of users. Also, gpiozero supports the pi 5, which, I think, RPI.GPIO does not. However, Jetson Nano and Coral will no longer be supported. Any suggestions? (Is Seeed Studio's team already rebuilding this with something different?)

**Comment by quietCoder500** [comment]
Another option is CircuitPython. This would provide support for Coral as well (maybe Jetson Nano) but this may make things complicated for the end user.

**Comment by is-qian** [comment]
In #77, these modules have been rewritten.

**Comment by quietCoder500** [comment]
Okay, thanks @is-qian.

**Pull request closed without merging**
